K_LADDER_RESOLUTION = "RESOLUTION"
K_LADDER_FPS = "FPS"

K_LADDER_TARGET_BR = "TARGET_BR"
K_LADDER_MIN_BR = "MIN_BR"
K_LADDER_MAX_BR = "MAX_BR"

K_LADDER_CRF = "CRF"

K_LADDER_THREADS_PASS_1 = "THREADS_PASS_1"
K_LADDER_TILES_PASS_1 = "TILES_PASS_1"
K_LADDER_SPEED_PASS_1 = "SPEED_PASS_1"

K_LADDER_THREADS_PASS_2 = "THREADS_PASS_2"
K_LADDER_TILES_PASS_2 = "TILES_PASS_2"
K_LADDER_SPEED_PASS_2 = "SPEED_PASS_2"

