K_RESCALING_METHOD_KEYFRAMES_APPROACH = "keyframes_method"

K_RESCALING_METHOD_KEYFRAMES_GOP = "gop"
K_RESCALING_METHOD_KEYFRAMES_CONSTANT = "constant"
K_RESCALING_METHOD_KEYFRAMES_FORCE_KEYS = "force_keys"

K_RESCALING_METHOD_GOP_SECONDS = "gop_seconds"
K_RESCALING_METHOD_SEGMENT_SECONDS = "segment_seconds"
K_RESCALING_METHOD_FORCED_INDEXES_LIST = "keyframes_indexes_list"
K_RESCALING_METHOD_FORCED_TIMESTAMPS_LIST = "keyframe_timestamps_list"



